config/routes.rb
Blogcms::Application.routes.draw do

  resources :about_me

  resources :articles do
    resources :answers
  end
  root to:"articles#index"

end

app/models/about_me.rb
class AboutMe < ActiveRecord::Base
  attr_accessible :content, :name

  validates :content, :name, :presence => true

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  attr_accessible :article_id, :name, :status

  validates :status, :name, :presence => true

  belongs_to :article

  belongs_to :replies, :class_name => "Answer", :foreign_key => "answer_id"
  
end

app/models/article.rb
class Article < ActiveRecord::Base
  attr_accessible :content, :name

  validates :name, :content, :presence => true

  has_many :answers, dependent: :destroy

end

app/controllers/about_me_controller.rb
class AboutMeController < ApplicationController
  # GET /about_mes
  # GET /about_mes.json
  def index
    @about_mes = AboutMe.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @about_mes }
    end
  end

  # GET /about_mes/1
  # GET /about_mes/1.json
  def show
    @about_me = AboutMe.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @about_me }
    end
  end

  # GET /about_mes/new
  # GET /about_mes/new.json
  def new
    @about_me = AboutMe.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @about_me }
    end
  end

  # GET /about_mes/1/edit
  def edit
    @about_me = AboutMe.find(params[:id])
  end

  # POST /about_mes
  # POST /about_mes.json
  def create
    @about_me = AboutMe.new(params[:about_me])

    respond_to do |format|
      if @about_me.save
        format.html { redirect_to @about_me, notice: 'About me was successfully created.' }
        format.json { render json: @about_me, status: :created, location: @about_me }
      else
        format.html { render action: "new" }
        format.json { render json: @about_me.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /about_mes/1
  # PUT /about_mes/1.json
  def update
    @about_me = AboutMe.find(params[:id])

    respond_to do |format|
      if @about_me.update_attributes(params[:about_me])
        format.html { redirect_to @about_me, notice: 'About me was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @about_me.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /about_mes/1
  # DELETE /about_mes/1.json
  def destroy
    @about_me = AboutMe.find(params[:id])
    @about_me.destroy

    respond_to do |format|
      format.html { redirect_to about_mes_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  # GET /answers
  # GET /answers.json
  before_filter :get_article

  def get_article
    @article=Article.find(params[:article_id])
  end

  def index
    @answers = @article.answers

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @answers }
    end
  end

  # GET /answers/1
  # GET /answers/1.json
  def show
    @answer = @article.answers.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @answer }
    end
  end

  # GET /answers/new
  # GET /answers/new.json
  def new
    @answer = Answer.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @answer }
    end
  end

  # GET /answers/1/edit
  def edit
    @answer = Answer.find(params[:id])
  end

  # POST /answers
  # POST /answers.json
  def create
    @answer = @article.answers.new(params[:answer])

    respond_to do |format|
      if @answer.save
        format.html { redirect_to [@article, @answer], notice: 'Answer was successfully created.' }
        format.json { render json: [@article, @answer], status: :created, location: [@article, @answer] }
      else
        format.html { render action: "new" }
        format.json { render json: [@article, @answer.errors], status: :unprocessable_entity }
      end
    end
  end

  # PUT /answers/1
  # PUT /answers/1.json
  def update
    @answer = @article.answers.find(params[:id])

    respond_to do |format|
      if @answer.update_attributes(params[:answer])
        format.html { redirect_to [@article, @answer], notice: 'Answer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /answers/1
  # DELETE /answers/1.json
  def destroy
    @answer = Answer.find(params[:id])
    @answer.destroy

    respond_to do |format|
      format.html { redirect_to answers_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @articles }
    end
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    @article = Article.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @article }
    end
  end

  # GET /articles/new
  # GET /articles/new.json
  def new
    @article = Article.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @article }
    end
  end

  # GET /articles/1/edit
  def edit
    @article = Article.find(params[:id])
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(params[:article])

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render json: @article, status: :created, location: @article }
      else
        format.html { render action: "new" }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /articles/1
  # PUT /articles/1.json
  def update
    @article = Article.find(params[:id])

    respond_to do |format|
      if @article.update_attributes(params[:article])
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    respond_to do |format|
      format.html { redirect_to articles_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/about_mes_helper.rb
module AboutMesHelper
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/about_me/_form.html.erb
<%= form_for(@about_me) do |f| %>
  <% if @about_me.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@about_me.errors.count, "error") %> prohibited this about_me from being saved:</h2>

      <ul>
      <% @about_me.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">

      <script type="text/javascript">
      tinyMCE.init({
        // General options
        mode : "textareas",
        theme : "advanced",
        width: '100%',
        height: 400,
        autoresize_min_height: 400,
        autoresize_max_height: 800,
        language: "pl",
        plugins : "autolink,lists,spellchecker,pagebreak,style,layer,table,save,advhr,advimage,advlink,emotions,iespell,inlinepopups,insertdatetime,preview,media,searchreplace,print,contextmenu,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras,template,autoresize",

        // Theme options
        theme_advanced_buttons1 : "save,newdocument,|,bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,|,styleselect,formatselect,fontselect,fontsizeselect",
        theme_advanced_buttons2 : "cut,copy,paste,pastetext,pasteword,|,search,replace,|,bullist,numlist,|,outdent,indent,blockquote,|,undo,redo,|,link,unlink,anchor,image,cleanup,help,code,|,insertdate,inserttime,preview,|,forecolor,backcolor",
        theme_advanced_buttons3 : "tablecontrols,|,hr,removeformat,visualaid,|,sub,sup,|,charmap,emotions,iespell,media,advhr,|,print,|,ltr,rtl,|,fullscreen",
        theme_advanced_buttons4 : "insertlayer,moveforward,movebackward,absolute,|,styleprops,spellchecker,|,cite,abbr,acronym,del,ins,attribs,|,visualchars,nonbreaking,template,blockquote,pagebreak,|,insertfile,insertimage",
        theme_advanced_toolbar_location : "top",
        theme_advanced_toolbar_align : "left",
        theme_advanced_statusbar_location : "bottom",

        // Skin options
        skin : "o2k7",
        skin_variant : "silver",

        // Example content CSS (should be your site CSS)
        content_css : "assets/application.css",

        // Drop lists for link/image/media/template dialogs
        template_external_list_url : "js/template_list.js",
        external_link_list_url : "js/link_list.js",
        external_image_list_url : "js/image_list.js",
        media_external_list_url : "js/media_list.js",

        // Replace values for the template plugin
        template_replace_values : {
                username : "Some User",
                staffid : "991234"
      }
    });
    </script>
    <%= f.label :content %><br />
    <%= f.text_area :content, :class => "tinymce" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/about_me/edit.html.erb
<h1>Editing about_me</h1>

<%= render 'form' %>

<%= link_to 'Show', @about_me %> |
<%= link_to 'Back', about_me_path %>

app/views/about_me/htmlerb/index.html.erb
<h1>Listing about_mes</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Content</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @about_mes.each do |about_me| %>
  <tr>
    <td><%= about_me.name %></td>
    <td><%= about_me.content %></td>
    <td><%= link_to 'Show', about_me %></td>
    <td><%= link_to 'Edit', edit_about_me_path(about_me) %></td>
    <td><%= link_to 'Destroy', about_me, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New About me', new_about_me_path %>

app/views/about_me/index.html.haml
%section#about_me
  - @about_mes.reverse_each do |about_me|
    %article.about_me{:id => "about_me-#{about_me.id}"}
      %ul#artykuly.box
        %li
          %header#tytul.artykuly-post
            %h1= about_me.name
        %li
          %p#tresc= raw about_me.content
        %br/
        %em
          = link_to 'Edycja', edit_about_me_path(about_me)
          | #{link_to 'Back', articles_path}

app/views/about_me/new.html.erb
<h1>New about_me</h1>

<%= render 'form' %>

<%= link_to 'Back', about_mes_path %>

app/views/about_me/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @about_me.name %>
</p>

<p>
  <b>Content:</b>
  <%= @about_me.content %>
</p>


<%= link_to 'Edit', edit_about_me_path(@about_me) %> |
<%= link_to 'Back', about_me_path %>

app/views/answers/_form.html.erb
<%= form_for([@article, @answer]) do |f| %>
  <% if @answer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@answer.errors.count, "error") %> prohibited this answer from being saved:</h2>

      <ul>
      <% @answer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :status %><br />
    <%= f.text_area :status %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/answers/edit.html.erb
<h1>Editing answer</h1>

<%= render 'form' %>

<%= link_to 'Show', @answer %> |
<%= link_to 'Back', answers_path %>

app/views/answers/htmlerb/new.html.erb
<h1>New answer</h1>

<%= render 'form' %>

<%= link_to 'Back', article_answers_path %>

app/views/answers/index.html.erb
<h1>Listing answers</h1>

<table>
  <tr>
    <th>Article</th>
    <th>Status</th>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @answers.each do |answer| %>
  <tr>
    <td><%= answer.article_id %></td>
    <td><%= answer.status %></td>
    <td><%= answer.name %></td>
    <td><%= link_to 'Show', [@article, answer] %></td>
    <td><%= link_to 'Edit', edit_article_answer_path([@article, answer]) %></td>
    <td><%= link_to 'Destroy', [@article, answer], method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Answer', new_article_answer_path %>

app/views/answers/new.html.haml
%header
  Nowy Komentarz

= render 'form'

= link_to 'Wroc', article_path(@article)

app/views/answers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Article:</b>
  <%= @answer.article_id %>
</p>

<p>
  <b>Status:</b>
  <%= @answer.status %>
</p>

<p>
  <b>Name:</b>
  <%= @answer.name %>
</p>


<%= link_to 'Edit', edit_article_answer_path(@answer) %> |
<%= link_to 'Back', article_answers_path %>

app/views/articles/_artykul.html.haml
%section
  - @articles.reverse_each do |article|
    %article.news{:id => "news-#{article.id}"}
      %ul#artykuly.box
        %li
          %header#tytul.artykuly-post
            %h1= link_to article.name, article
        %li
          %p#tresc= raw truncate(article.content, :length => 1500, :separator => ' ')
          %br/
          %span= link_to 'Czytaj więcej', article
          %em
            = link_to 'Edycja', edit_article_path(article)
            | #{link_to 'Usun wpis', article, method: :delete, data: {confirm: 'Jestes pewien?'}}

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/edit.html.haml
%section#ramka
  %article#news
    %ul
      %li
        %header#tytul.artykuly-post
          %h1 Edytuj Wpis
    =render 'form'
    %br/
    %span= link_to 'Show', @article
    %em= link_to 'Cofnij', articles_path

app/views/articles/htmlerb/edit.html.erb
%section#ramka
  %article#news
    %ul
      %li
        %header#tytul.artykuly-post
          %h1 Edytuj Wpis
    =render 'form'
    %span= link_to 'Show', @article
    %em= link_to 'Bacl', articles_path

app/views/articles/htmlerb/index.html-kopia.erb
<div id="middle" align="center" >

	<table>
  		<tr>
    		<th></th>
    		<th></th>
    		<th></th>
    		<th></th>
    		<th></th>
  		</tr>
  
	<% @articles.reverse_each do |article| %>
      
      <tr>
        
    		<td><center>
          <%= image_tag("papyrus1.png") %>
          <div id="artykul" align="center" style="background-image: url(/assets/papyrus2.png);"><h1><%= article.name %></h1><%= raw article.content %>
          </div>
          <%= image_tag("papyrus3.png") %>

        </td>
        
    		<td></td>
  		</tr>
  		<tr>
    		<td><center><%= link_to 'Show', article %> <%= link_to 'Edit', edit_article_path(article) %> <%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %></center></td>
    		<td><center></center></td>
    		<td><center></center></td>
  		</tr>
      <tr>

        <center><td>--------------------------------------------------------------------------------------------------</td></center>
        
      </tr>

	<% end %>
  
	</table>
	<br />

	<%= link_to 'New Article', new_article_path %>
  

</div>

</center>

app/views/articles/htmlerb/index3.html.erb
<center>
<h1>Lista Artykulow</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @articles.each do |article| %>
  <tr>
    <td><center><%= article.name %></center><br /><center><%= raw article.content %></center></td>
    <td></td>
  </tr>
  <tr>
    <td><center><%= link_to 'Show', article %> <%= link_to 'Edit', edit_article_path(article) %> <%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %></center></td>
    <td><center></center></td>
    <td><center></center></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Article', new_article_path %>
</center>

app/views/articles/htmlerb/index4kopianajnowsza.html.erb
<div id="content">
  <section>
    <article id="news">
      <% @articles.reverse_each do |article| %>  
        <ul id="artykuly" class="box">
          <li><header id="tytul" class="artykuly-post"><h1><%= link_to article.name, article %></h1></header></li>
          <li><p id="tresc"><%= raw truncate(article.content, :length => 1500, :separator => ' ') %></p>
            <br>
            <span><%= link_to 'Czytaj więcej', article %></span>
            <em><%= link_to 'Edycja', edit_article_path(article) %> | <%= link_to 'Usun wpis', article, method: :delete, data: { confirm: 'Jestes pewien?' } %></em>
          </li>
        </ul>
        <center></center>
      <% end %>
    </article>
  
    <center><%= link_to 'Nowy Artykul', new_article_path %></center>
  </section>
</div>

app/views/articles/htmlerb/new.html.erb
<center>
<h1>New article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>
</center>

app/views/articles/htmlerb/new.html.haml
%center
  %h1 New article
  = render 'form'
  = link_to 'Back', articles_path

app/views/articles/htmlerb/show.html-kopia1.erb
<p id="notice"><%= notice %></p>
<div id="content">
  <section id="">
    <article id="">
        <ul id="artykuly">
          <li><header id="tytul"><h1><%= @article.name %></h1></header></li>
          <li><p id="tresc"><%= raw @article.content %></p></li>
        </ul>
        <center><%= link_to 'Edit', edit_article_path(@article) %> | <%= link_to 'Back', articles_path %></center>
    
    </article>
  
    
  </section>
</div>
 

app/views/articles/index.html.haml
=render 'artykul'

app/views/articles/new.html.haml
%p#notice= notice
%section#ramka
  %article#news
    %ul
      %li
        %header#tytul.artykuly-post
          %h1 Nowy Wpis
    =render 'form'
    %em= link_to 'Back', articles_path

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>
<div id="content">
  <section id="">
    <article id="">
        <ul id="artykuly">
          <li><header id="tytul"><h1><%= @article.name %></h1></header></li>
          <li><p id="tresc"><%= raw @article.content %></p></li>
        </ul>
        <center><%= link_to 'Edit', edit_article_path(@article) %> | <%= link_to 'Back', articles_path %></center>
    
    </article>
  
    
  </section>
</div>
 

app/views/articles/show.html.haml
%p#notice= notice
%section
  %article.news{:id => "news-#{@article.id}"}
    %ul#artykuly
      %li
        %header#tytul.artykuly-post
          %h1= @article.name
      %li
        %p#tresc= raw @article.content
        %br/
        = @article.created_at
        %em
          = link_to 'Edycja', edit_article_path(@article)
          | #{link_to 'Back', articles_path}

%section#komentarze
  %article
    %header
      %h1 Komentarze:
    - if @article.answers.each.count == 0
      %p#brak_komentarzy
        Brak Komentarzy!!! Badz pierwszy!
    - else
      - @article.answers.each do |answer|
        %ul.komcie{:id => "koment-#{answer.id}"}
          %li
            %p#komenty1.komentarze-post= answer.status
          %li
            %p#nazwa_usera
              Autor:
              = answer.name
          %br/
          %p#odpowiedzi Odpowiedzi:


%br/

#nowykomentarz
  %b
    =link_to 'Dodaj komentarz', new_article_answer_path([@article, @answer])

app/views/layouts/application.html.haml
!!! 5
%html{:lang => "pl"}
  %head
    %title
      -if defined? @article.name
        Wpis: 
        =@article.name
      -else
        Proque CMS Blog!
    =stylesheet_link_tag "application", :media => "all"
    =javascript_include_tag "application"
    =tinymce_assets
    =csrf_meta_tags
    %link{:href => "http://fonts.googleapis.com/css?family=Patrick+Hand+SC", :rel => "stylesheet", :type => "text/css"}/
  %body
    %p{:style => "color: green"}= flash[:notice]
    %header
      %a#logo{:href => root_path}
        %h1.texthide Porque & CMS Blog
    %nav#primary
      %ul
        %li= link_to 'Home', root_path
        %li= link_to 'O mnie', about_me_index_path
        %li= link_to 'Kontakt', root_path
    #wrap
      = yield

      %footer#primary-foot
        %section#history
          %header
            %h1 Co uzyte?
          %p
            Do tego projektu w ramach nauki zostal uzyty: ror, html5 i css3.
            %br/
        %section#info
          %nav#footer-nav
            %ul
              %li= link_to 'Home', root_path
              %li= link_to 'O mnie', root_path
              %li= link_to 'Kontakt', root_path
              %li= link_to 'Nowy wpis', new_article_path
          %p.copyright
            \© 2013 wykop.pl/ludzie/porque/, Blog CMS by Porque
            %br/
            Pierwsza odslona, psuedo systemu cms do bloga.

app/views/layouts/htmlerb/application-kopia.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
       "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
  <meta http-equiv="content-type" content="text/html;charset=UTF-8" />
  <title>
  <% if defined? @article.name %>
    Porque: <%= @article.name %>
  <% else %>
    <%= "Blog Porque" %>
  <% end %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= tinymce_assets %>
  <%= csrf_meta_tags %>
</head>
<body style="background-image: url(/assets/drewno.jpg);">

<p style="color: green"><%= flash[:notice] %></p>

<div id="container" align="center">
	<div id="logo">
    <%= link_to image_tag("blogheader.jpg"), root_path %>
	</div>

  <div id="menu">
    <h1>Test Menu</h1>
  </div>

  <div id="left">
    <h1>Test Menu Lewe</h1>
  </div>

	<%= yield %>

  <div id="right">
    <h1>Test Menu Prawe</h1>
  </div>

  <center><div id="footer" align="center">
    <br>
    <%= link_to 'Blog created by Porque!', root_path %>
  </div>

</div>

</body>
</html>

app/views/layouts/htmlerb/application-kopia2.html.erb
<!DOCTYPE html>
<html lang="pl">
<head>
<meta charset="utf-8" />
  <title>
  <% if defined? @article.name %>
    Porque: <%= @article.name %>
  <% else %>
    <%= "Blog Porque" %>
  <% end %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= tinymce_assets %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Patrick+Hand+SC' rel='stylesheet' type='text/css'>
</head>
<body>

<p style="color: green"><%= flash[:notice] %></p>
<header>
    <a href="<%= root_path %>" id="logo"><h1 class="texthide">Border &amp; Radius Brewhouse</h1></a>
</header> 

<nav id="primary">
      <ul>
        <li><%= link_to 'Home', root_path %></li>
        <li><%= link_to 'O mnie', root_path %></li>
        <li><%= link_to 'Kontakt', root_path %></li>
        <li><%= link_to 'Nowy artykul', new_article_path %></li>
      </ul>
</nav>

<div id="wrap">

	<%= yield %>


  <footer id="primary-foot">
    <section id="history">
      <header><h1>Co uzyte?</h1></header>
      <p>Do tego projektu w ramach nauki zostal uzyty: ror, html5 i css3.<br /> 
      
    </section>
    
    <section id="info">
      <nav id="footer-nav">
        <ul>
          <li><a href="#">Home</a></li>
          <li><a href="#">O mnie</a></li>
          <li><a href="#">Kontakt</a></li>
        </ul>
      </nav>
      
      <p class="copyright">&copy; 2013 wykop.pl/ludzie/porque/, Blog CMS by Porque<br />
      Pierwsza odslona, psuedo systemu cms do bloga.</p>
    </section>
  
  </footer>

</div>

</body>
</html>

app/views/layouts/htmlerb/application-kopia3.html.erb
<!DOCTYPE html>
<html lang="pl">
<head>
<meta charset="utf-8" />
  <title>
  <% if defined? @article.name %>
    Porque: <%= @article.name %>
  <% else %>
    <%= "Blog Porque" %>
  <% end %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= tinymce_assets %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Patrick+Hand+SC' rel='stylesheet' type='text/css'>
</head>
<body>

<p style="color: green"><%= flash[:notice] %></p>
<header>
    <a href="<%= root_path %>" id="logo"><h1 class="texthide">Border &amp; Radius Brewhouse</h1></a>
</header> 

<nav id="primary">
      <ul>
        <li><%= link_to 'Home', root_path %></li>
        <li><%= link_to 'O mnie', root_path %></li>
        <li><%= link_to 'Kontakt', root_path %></li>
        <li><%= link_to 'Nowy artykul', new_article_path %></li>
      </ul>
</nav>

<div id="wrap">

	<%= yield %>


  <footer id="primary-foot">
    <section id="history">
      <header><h1>Co uzyte?</h1></header>
      <p>Do tego projektu w ramach nauki zostal uzyty: ror, html5 i css3.<br /> 
      
    </section>
    
    <section id="info">
      <nav id="footer-nav">
        <ul>
          <li><a href="#">Home</a></li>
          <li><a href="#">O mnie</a></li>
          <li><a href="#">Kontakt</a></li>
        </ul>
      </nav>
      
      <p class="copyright">&copy; 2013 wykop.pl/ludzie/porque/, Blog CMS by Porque<br />
      Pierwsza odslona, psuedo systemu cms do bloga.</p>
    </section>
  
  </footer>

</div>

</body>
</html>